pc-638-ONN release maken en release configuratie aanpassen
Klantinteractie-Servicesysteem/.github pull request #86
Opened 2024-12-18 09:53 UTC by githubjimmeicatt

kleine aanpassing handleiding

2025-01-06 17:49 UTC, sytskevanhasselt commented on docs/INSTALLATION.md
Twee vragen:

Je hebt hier bij Client secret en client ID expliciet toegevoegd: 'dan deze leeg laten'. 
Moet er bij `INTERNE_TAAK_TOKEN` niet iets vergelijkbaars staan? 
Daar staat nu
(niet te gebruiken met `INTERNE_TAAK_CLIENT_SECRET` en `INTERNE_TAAK_CLIENT_ID`)

Moet dat dan niet ook worden: 
niet te gebruiken met `INTERNE_TAAK_CLIENT_SECRET` en `INTERNE_TAAK_CLIENT_ID`, dan deze twee leeglaten)

Daarnaast: waarom heb je dit hierbij gezet? 
want ik realiseer mij dat ik iet weet wat hier precies bedoeld wordt. 

Is het wellicht beter om een <details>  toe te voegen, zoals dnu ook is bij interne Taak Token?

2025-01-06 17:50 UTC, sytskevanhasselt requested changes
Graag even kijken naar mijn comments, over _de uitleg bij client_id en client_secret, voor Interne taak, en voor Medewerker.

2025-01-09 10:40 UTC, githubjimmeicatt commented on docs/INSTALLATION.md
Andersom heb ik het niet getest vandaar, maar hoe dan ook als we de token gebruiken mag de client secret en id ook gewoon leeg zijn. Want die worden dan niet gebruikt. 

Dit is wel een belangijk en houd ik graag hierin want als dit niet als lege value in de release variables of powershell script staat en bijv helemaal weg laat (ligt eraan hoe je deployed) dan werkt het niet en krijg je errors in de pods.

2025-01-09 10:41 UTC, githubjimmeicatt commented on docs/INSTALLATION.md
> +| `MEDEWERKER_OBJECTEN_CLIENT_SECRET`  | Client Secret voor de Objecten API voor medewerkers <br/> **(niet te gebruiken i.c.m. MEDEWERKER_OBJECTEN_TOKEN, dan deze leeg laten)**            |
Ja hier ook

2025-01-09 16:44 UTC, sytskevanhasselt approved these changes

2025-01-09 16:45 UTC, merged