pc-638-ONN release maken en release configuratie aanpassen
Klantinteractie-Servicesysteem/.github pull request #87
Opened 2024-12-18 09:59 UTC by githubjimmeicatt

toevoegen env variables

2025-01-06 17:55 UTC, sytskevanhasselt commented
@githubjimmeicatt deze kan ik moeilijk reviewen. 

@felixcicatt , of @PascalIcatt , kan één van jullie beoordelen of deze ok is?

2025-01-09 13:29 UTC, felixcicatt requested changes

2025-01-09 13:29 UTC, felixcicatt commented on docs/scripts/install_kiss.ps1
> +    --from-literal=MANAGEMENTINFORMATIE_API_KEY=$(MANAGEMENTINFORMATIE_API_KEY) `
Deze staat al bij de secrets. Verder prima!

2025-01-13 09:41 UTC, felixcicatt approved these changes

2025-01-13 09:42 UTC, merged